### ISSUE TITLE
Create Plugin For PreactX Compatibility

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-preactx-plugin#1]
# Motivation
We want to be able to create a plugin.

# Tasks
- [x] Import Dependencies.
- [x] Use the First Preact App as a plugin.
- [x] Publish to NPM.
- [x] Verify that it works on the first-preact-app project.
