### ISSUE TITLE
Remove Extra Step of adding Module Aliases in main project

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-preactx-plugin#3]
# Motivation
We want to keep the interface as similar to the original plugin as possible.

# Task Implementation
- [x] Move react and react-dom to dev dependencies.
- [x] Move all other modules to peer Dependencies.
- [x] Update instructions to suit that purpose.
- [x] publish new version on NPM
