### ISSUE TITLE
Remove necessity for React and React-Dom

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-preactx-plugin#6]
# Motivation
We want to be able to use this without needing react and react-dom.

# Tasks
- [ ] Remove react and react-dom.
- [ ] add link-module-alias.
- [ ] Update package.json to be able to execute link-module-alias.
- [ ] Update
